version: "3.7"

services:
  verifier:
    image: pactfoundation/pact-ref-verifier:latest
    depends_on:
      api:
        condition: service_healthy
    environment:
      - PACT_DIR
      - PROVIDER
      - REPORT_DIR
    volumes:
      - type: bind
        read_only: true
        source: $PACT_DIR
        target: /pacts
      - type: bind
        read_only: false
        source: $REPORT_DIR
        target: /verification
    command:
      - --dir=/pacts
      - --state-change-url=http://api:3000/state
      - --provider-name=$PROVIDER
      - --hostname=api
      - --port=3000
      - --base-path=/prism
      - --json=/verification/report.json
