version: "3.7"

services:
  prism:
    image: prism
    build:
      dockerfile: prism.dockerfile
      context: ./
    environment:
      - OPENAPI_DIR
      - OPENAPI_FILE=openapi.yml
    volumes: [$OPENAPI_DIR:/openapi]
    command: ./entrypoint.sh
    ports:
      - "3000:3000"

