version: "3.7"

services:
  prism:
    image: prism
    build:
      dockerfile: prism.dockerfile
      context: ./
    environment:
      - OPENAPI_SPEC
    volumes:
      - .:/stateful-prism
    command:
      - sh
      - -c
      - |
        echo -e '${OPENAPI_SPEC}' > ./openapi.yml
        prism mock --host=0.0.0.0 ./openapi.yml
    ports:
      - "4010:4010"
